<nav class="navbar is-dark">
  <ul>
    <li>
      <a class="navbar-item has-text-light" href="/"> Home</a>
    </li>
    <li>
      <a class="navbar-item has-text-light" href="contactus"> Contact Us</a>
    </li>
    <li>
      <a class="navbar-item has-text-light" href="offeredsportsanddraws"> Offered Sports and Draws</a>
    </li>
  </ul>
</nav>

<style>
  a {
    font-family: "Quattrocento Sans";
    font-size: 20px;
  }
</style>
