<nav class="navbar is-dark">
  <a class="navbar-item has-text-light" href="/"> Home</a>
  <br />
  <a class="navbar-item has-text-light" href="contactus"> Contact Us</a>
  <br />
  <a class="navbar-item has-text-light" href="offeredsportsanddraws"> Offered Sports and Draws</a>
  <br />
  <a class="navbar-item has-text-light" href="results"> Results</a>
  <br />
</nav>

<style>
  a {
    font-family: "Quattrocento Sans";
    font-size: 20px;
    text-align: center;
  }
</style>
