<nav class="navbar is-dark" aria-label="breadcrumbs">
  <a class="navbar-item has-text-light" href="/"> Home</a>
  <br />
  <a class="navbar-item has-text-light" href="contactus"> Contact Us</a>
  <br />
  <a class="navbar-item has-text-light" href="offeredsportsanddraws"> Offered Sports and Draws</a>
  <br />
  <a class="navbar-item has-text-light" href="results"> Results</a>
  <br />
</nav>

<!-- <nav class="navbar is-dark breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="/">Home</a></li>
    <li><a href="contactus">Contact Us</a></li>
    <li><a href="offeredsportsanddraws">Offered Sports and Draws</a></li>
    <li><a href="results">Results</a></li>
  </ul>
</nav> -->

<style>
  a {
    font-family: "Quattrocento Sans";
    font-size: 20px;
    text-align: center;
  }
</style>
